### PR TITLE
Create odisho eivazi

### PR DESCRIPTION
**Pull request by odibahal**

### CODE REVIEW

**Comment by odibahal** [comment]
please let us know what are you looking to develop in this game

**Comment by jamesreaver** [comment]
It is just a college exercise.

**Comment by odibahal** [comment]
Ok, my friend and I trying to add more stuff on it

**Comment by vakellian** [comment]
@giacomoguerci Hello, 
I'm the guy @odibahal was referring too. Just like you, we are also working on a college assignment, yayyy! I saw your code and am working on some contributions, working on fleshing out the game out more by adding GUIs and more dynamic fun stuff. And my associate will too.

**Pull request closed without merging**
